version: '3.8'

services:
  backend:
    build: ./backend
    image: book-me-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  frontend:
    build: ./frontend
    image: book-me-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped 